- name: configure tomcat for jenkins
  hosts: all
  tasks:
   - name: install tomcat9
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tomcat9, b: present, c: yes}
      - {a: tomcat9-admin, b: present, c: no}
   - name: copy users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: restart tomcat9
     service:
      name: tomcat9
      state: restarted
...

